name: Compilar Python a EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compilar con PyInstaller
      run: |
        pyinstaller --onefile --noconsole REPORTE DE MTTOS.py

    - name: Subir el archivo EXE como Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Programa-EXE
        path: dist/*.exe
